<template>
  <div
    class="
      fixed
      left-4
      w-72
      h-72
      bg-blue-400
      opacity-50
      rounded-full
      mix-blend-multiply
      filter
      blur-xl
      animate-blob
      animation-delay-2000
    "
  ></div>
  <div
    class="
      fixed
      right-4
      w-72
      h-72
      bg-yellow-400
      opacity-50
      rounded-full
      mix-blend-multiply
      filter
      blur-xl
      animate-blob
      animation-delay-4000
    "
  ></div>
  <div
    class="
      fixed
      bottom-0
      left-50
      w-72
      h-72
      bg-rose-400
      opacity-50
      rounded-full
      mix-blend-multiply
      filter
      blur-xl
      animate-blob
    "
  ></div>
</template>